services:
    outlandish_routemaster.query_manager:
        class: Outlandish\RoutemasterBundle\Manager\QueryManager

    outlandish_routemaster.listener.unhook:
        class: Outlandish\RoutemasterBundle\EventListener\UnhookListener
        tags:
            - name: kernel.event_listener
              event: kernel.request
              method: onKernelRequest