services:
    outlandish_routemaster.query_manager:
        class: Outlandish\RoutemasterBundle\Manager\QueryManager

    outlandish_routemaster.subscriber.hook:
        class: Outlandish\RoutemasterBundle\EventListener\HookSubscriber
        tags:
            - name: kernel.event_subscriber